### ISSUE TITLE
'generate ores' not working

### ISSUE THREAD

**Issue by paramat** [SmallJoker/lualandmg#1]
Are you using very latest MT engine? or what commit are you on?

'generate ores' should certainly be after 'set data' otherwise 'set data' overwrites the added ores (but of course no ores would be added to a mapchunk full of "air" which is what the vm is before 'set data'.

Also, `vm:write_to_map(data)` doesn't need a data argument, that was a mistake hmmmm made in his LVM example and which we all copied.

I can't see the cause of your bug yet.

**Comment by SmallJoker** [comment]
I noticed that the decorations and ores are generated as soon another mod updates the mapblocks during the generation process. This means, that writing to the map must happen after the ores/decorations are generated, as these functions don't do that themselves.
My fault was first) to override the map by set_data and second) to not write to the map after calling the generation functions. With this little change it works fine now:
https://github.com/SmallJoker/lualandmg/commit/b72ef91#diff-d7d74284e2e39f6c06d199c8e2bedbd0R411

**Comment by paramat** [comment]
Good, 'generate ores/decorations' only adds them to the 'vm' (and not to the flat array 'data'), you then need to 'write the vm to map' afterwards.
